version: '3'
services:
  bot:
    build: .
    depends_on:
      - redis
    network_mode: host
    environment:
      RTM_HUB_URL: http://172.23.239.55:5000/ChatHub
      REDIS_URL: http://redis:6379
  redis:
    image: redis:3.2-alpine
    network_mode: host


