version: '3'
services:
  bot:
    container_name: bot
    build: .
    depends_on:
      - redis
    labels:
        SERVICE_80_NAME: bot
        SERVICE_TAG: bot
    environment:
      RTM_HUB_URL: http://13.126.8.255/rtm/ChatHub
      REDIS_URL: http://redis
      REDIS_HOST: redis
      SOLUTION_EXPLORER_API: http://13.126.8.255/solution
      TICKET_MANAGEMENT_API: http://13.126.8.255/tickets
    restart: always
  redis:
    image: redis:3.2-alpine
    restart: always
